### ISSUE TITLE
mwcceppc error

### ISSUE THREAD

**Issue by z0mbieslayer** [doldecomp/smg#1]
I'm having an issue while compiling where I get this error:

`mwcceppc.exe: processor Gecko is not supported by the current set of licenses. Please contact <license@freescale.com>
mwcceppc.exe: for licensing needs`

I haven't been able to find online anyone else with this error so I have no clue what to do. Any help would be greatly appreciated.

**Comment by shibbo** [comment]
You have the wrong license for the compiler, so you can't use gekko. You have to crack the DLL included with the compilers.

**Comment by z0mbieslayer** [comment]
I hate to ask, but how would I crack the dll?

**Comment by shibbo** [comment]
Do you have Discord? Just add me as a friend, shibboleet#1407 and I will send you what you need.

**Comment by z0mbieslayer** [comment]
It says you aren't accepting friend requests. My discord is squeakycleanswine#1231 if you wanna add me instead

**Comment by shibbo** [comment]
Issue has been solved, closing.

**Comment by MasterofGalaxies** [comment]
Could you send me the cracked DLLs? My Discord username is Galaxy Master#4446

**Comment by RevoSucks** [comment]
Please do not request that on Github.
